### PR TITLE
Added non-Windows warnings

### PR DESCRIPTION
**Pull request by IronManMark20**
I added the solution as discussed [here](https://github.com/pyqt/python-qt5/issues/9)

### CODE REVIEW

**Comment by mottosso** [comment]
Looks good @IronManMark20 

The next thing we need to figure out is how to get this update to PyPI, as the latest commit is for 5.4 which is too large for PyPI, so we'll need to merge this pull-request with [this commit](https://github.com/pyqt/python-qt5/commit/48796e226fd9c53d7b96496973b7ee33f6c6c738) and create a new release for that.

Possibly as a separate branch, to keep it separate.

We could also merge it with the latest commit, and keep the installation on GitHub-only.

What are your thoughts?

**Comment by IronManMark20** [comment]
I think people who are told to `pip install python-qt5` won't necessarily know that the binaries are Windows only. What that means for the project is beyond me.

**Comment by mottosso** [comment]
I'm with you, it makes sense.

I made a new branch where your fix would make the most sense, could you re-target your pull-request to the branch 5.3? There should be a drop-down at the top of either this page, or when you first make the pull-request.

We'll merge it there, and I'll get this up to PyPI.

**Comment by IronManMark20** [comment]
Hmm.. no luck re-aiming a PR doesn't seem to be possible. -_- I'll just open a new one.

**Pull request closed without merging**
